### ISSUE TITLE
HTML File totally empty 

### ISSUE THREAD

**Issue by sakib2005** [sakib2005/MMU-Club-Registration-Portal#5]
admin-dashboard.html is totally doesn't have anything inside @JiaJun0207 

![image](https://github.com/sakib2005/MMU-Club-Registration-Portal/assets/73412648/bdf0b8d8-e51b-4ded-91bc-4dfc6f481a85)

**Comment by JiaJun0207** [comment]
this is in other folder. i think this html file just delete it
